"""add accounts and transactions

Revision ID: 29093b8194c1
Revises: e2f41b8119e3
Create Date: 2026-08-07 20:37:38.436491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "29093b8194c1"
down_revision: Union[str, Sequence[str], None] = "e2f41b8119e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.rename_table("expenses", "transactions")
    op.add_column(
        "transactions", sa.Column("account_id", sa.Integer(), nullable=True)
    )  # временно nullable!
    op.drop_column("transactions", "user_id")
    op.execute("""
    INSERT INTO accounts (name, balance, type, currency, owner_id)
    SELECT 'main', 0, 'card', 'BYN', id FROM users
""")
    op.execute("""
    UPDATE transactions
    SET account_id = (SELECT id FROM accounts WHERE name = 'main' LIMIT 1)
""")
    op.alter_column("transactions", "account_id", nullable=False)
    op.add_column(
        "category",
        sa.Column(
            "type", sa.String(length=8), server_default="expense", nullable=False
        ),
    )
    op.drop_column("users", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "currency",
            sa.VARCHAR(length=5),
            server_default=sa.text("'USD'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("category", "type")
    op.create_table(
        "expenses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name=op.f("expenses_category_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("expenses_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("expenses_pkey")),
    )
    op.drop_table("transactions")
    op.drop_table("accounts")
    # ### end Alembic commands ###
