"""add active_account_id to users

Revision ID: efd6cb955a0f
Revises: 29093b8194c1
Create Date: 2026-08-08 11:39:25.414872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd6cb955a0f'
down_revision: Union[str, Sequence[str], None] = '29093b8194c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'accounts', ['active_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_account_id')
    # ### end Alembic commands ###
